# vim: set ft=toml :


min_version = '2026.4.8'


[hooks]
postinstall = [{ task = 'hooks-install' }, 'pixi install --all']


[settings]
experimental = true
locked = true
lockfile = true
lockfile_platforms = ['macos-arm64']


[tasks.deploy]
env = { REMOTE_NAME = 'personal' }
run = [
  'git push -- "${REMOTE_NAME}"',
  'pixi run -- mkdocs gh-deploy --no-history --remote-name "${REMOTE_NAME}"',
]

[tasks.hooks-install]
hide = true
run = [{ task = 'hooks-uninstall' }, 'hk install --mise']

[tasks.hooks-uninstall]
hide = true
run = 'hk uninstall'

[tasks.lint]
run = 'hk fix --all'

[tasks.serve]
run = 'pixi run -- mkdocs serve --open'

[tasks.upgrade]
run = ['mise upgrade --local', 'pixi update']


[tools]
hk = 'latest'
pixi = 'latest'
pkl = 'latest'
