# vim: set ft=toml :


[workspace]
name = 'notes'
channels = ['conda-forge']
platforms = [
  'linux-64',
  'osx-arm64',
]


[dependencies]
python = { version = '>=3.14,<3.15' }


[pypi-dependencies]
zensical = { version = '*' }
