# vim: set ft=toml :


[workspace]
name = 'notes'
channels = ['conda-forge']
platforms = ['osx-arm64']


[dependencies]
python = { version = '>=3.14.3,<3.15' }


[pypi-dependencies]
mkdocs = { version = '>=1.6.1' }
mkdocs-macros-plugin = { version = '>=1.5.0' }
mkdocs-material = { version = '>=9.7.2', extras = ['git', 'imaging', 'recommended'] }
