# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

vars:
  VENV: '{{ .VENV | default ".venv" }}'
  MKDOCS: '{{ .VENV }}/bin/mkdocs'

includes:

  uv:
    taskfile: '.taskfile-library/include/uv'
    vars:
      PYTHON_MINOR_VERSION: '3.12'
      VENV: '{{ .VENV }}'

tasks:

  serve:
    deps: ['uv:venv']
    cmds:
      - '{{ .MKDOCS | shellQuote }} serve {{ if .ADDR }}--dev-addr {{ .ADDR | shellQuote }}{{ end }} {{ if not .NO_OPEN }}--open{{ end }}'

  deploy:
    deps: ['uv:venv']
    cmds:
      - task: 'push'
      - '{{ .MKDOCS | shellQuote }} gh-deploy --no-history --remote-name personal'

  push:
    cmds:
      - for: ['personal']
        cmd: 'git push -- {{ .ITEM | shellQuote }}'
