# vim: set ft=yaml :


name: 'Documentation'

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: 'sh -euo pipefail {0}'

permissions:
  contents: 'read'
  id-token: 'write'
  pages: 'write'

jobs:
  deploy:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    # switch to 'ubuntu-latest' when 'ubuntu-26.04' becomes latest
    # https://github.com/actions/runner-images/issues/14226
    runs-on: 'ubuntu-26.04'
    steps:
      - uses: 'actions/configure-pages@v6'
      - uses: 'actions/checkout@v7'
      - uses: 'jdx/mise-action@v4'
      - run: 'mise run build'
      - uses: 'actions/upload-pages-artifact@v5'
        with:
          path: 'site'
      - uses: 'actions/deploy-pages@v5'
        id: 'deployment'
