sequenceDiagram

  participant KC as macOS "login" keychain
  participant 1P as 1Password Connect

  participant LD as launchd
  participant ER as exec-resticprofile
  participant RP as resticprofile
  participant RE as restic
  participant RC as rclone

  participant PC as pCloud
  participant HC as Healthchecks.io

  LD ->> ER: Execute
  ER ->> KC: Request 1Password Connect token
  KC ->> ER: Receive 1Password Connect token
  ER ->> RP: Execute w/ 1P Connect token in env
  RP ->> 1P: Request healthcheck endpoint UUID
  1P ->> RP: Receive healthcheck endpoint UUID
  RP ->> HC: Ping healthcheck endpoint
  RP ->> RE: Execute
  RE ->> 1P: Request restic repo password
  1P ->> RE: Receive restic repo password
  RE ->> RC: Start HTTP server
  RC ->> 1P: Request rclone config password
  1P ->> RC: Receive rclone config password
  RC ->> RE: HTTP connection established

  loop Data transfer: backup, forget old snapshots
    RE ->> RC: HTTP
    RC ->> PC: HTTPS
    PC ->> RC: HTTPS
    RC ->> RE: HTTP
  end

  RE ->> RP: Return status
  RP ->> 1P: Request healthcheck endpoint UUID
  1P ->> RP: Receive healthcheck endpoint UUID
  RP ->> HC: Ping healthcheck endpoint w/ status and log file
